# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

name: Publish to PyPi

on:
  push:
    branches:
      - main

jobs:
  pypi-upload:
    runs-on: ubuntu-latest
    name: deploy
    environment:
      name: pypi
      url: https://pypi.org/p/rapidstream-cocotbext-axi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@master
      with:
        # To generate a valid version number setuptools_scm needs sufficient
        # git history.
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a source tarball
      run: >-
        python -m
        build
        --sdist
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
